package de.msiggi.sportsdata.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-05-03T15:44:11.223+02:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://msiggi.de/Sportsdata/Webservices", name = "SportsdataSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SportsdataSoap {

    /**
     * Gibt eine Liste aller Goals der als Parameter zu übergebenden Liga + Saison zurueck.
     */
    @WebMethod(operationName = "GetGoalsByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetGoalsByLeagueSaison")
    @RequestWrapper(localName = "GetGoalsByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetGoalsByLeagueSaison")
    @ResponseWrapper(localName = "GetGoalsByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetGoalsByLeagueSaisonResponse")
    @WebResult(name = "GetGoalsByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfGoal getGoalsByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );

    /**
     * Gibt eine Struktur von Sport-Spieldaten aller Spiele der Liga pro Saison zurueck. Als Parameter werden der Liga-Shortcut (z.B. 'bl1') sowie die Saison (aus GetAvailLeagues, z.B. '2007') erwartet.
     */
    @WebMethod(operationName = "GetMatchdataByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByLeagueSaison")
    @RequestWrapper(localName = "GetMatchdataByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByLeagueSaison")
    @ResponseWrapper(localName = "GetMatchdataByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByLeagueSaisonResponse")
    @WebResult(name = "GetMatchdataByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfMatchdata getMatchdataByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );

    /**
     * Gibt eine Struktur des nächsten anstehenden Spieles der als Parameter zu übergebenden Liga zurueck.
     */
    @WebMethod(operationName = "GetNextMatch", action = "http://msiggi.de/Sportsdata/Webservices/GetNextMatch")
    @RequestWrapper(localName = "GetNextMatch", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetNextMatch")
    @ResponseWrapper(localName = "GetNextMatchResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetNextMatchResponse")
    @WebResult(name = "GetNextMatchResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.Matchdata getNextMatch(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut
    );

    /**
     * Gibt die aktuelle Group (entspricht z.B. bei der Fussball-Bundesliga dem 'Spieltag') des als Parameter zu übergebenden leagueShortcuts (z.B. 'bl1') aus. Der aktuelle Spieltag wird jeweils zur Hälfte der Zeit zwischen dem letzten Spiel des letzten Spieltages und dem ersten Spiel des nächsten Spieltages erhöht.
     */
    @WebMethod(operationName = "GetCurrentGroup", action = "http://msiggi.de/Sportsdata/Webservices/GetCurrentGroup")
    @RequestWrapper(localName = "GetCurrentGroup", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetCurrentGroup")
    @ResponseWrapper(localName = "GetCurrentGroupResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetCurrentGroupResponse")
    @WebResult(name = "GetCurrentGroupResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.Group getCurrentGroup(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut
    );

    /**
     * Gibt eine Struktur des Spieles der als Parameter zu übergebenden MatchID zurueck.
     */
    @WebMethod(operationName = "GetMatchByMatchID", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchByMatchID")
    @RequestWrapper(localName = "GetMatchByMatchID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchByMatchID")
    @ResponseWrapper(localName = "GetMatchByMatchIDResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchByMatchIDResponse")
    @WebResult(name = "GetMatchByMatchIDResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.Matchdata getMatchByMatchID(
        @WebParam(name = "MatchID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int matchID
    );

    /**
     * Gibt eine Struktur des zuletzt ausgetragenen Spieles des als Parameter zu übergebenden Teams der ebenfalls zu übergebenen Liga zurueck.
     */
    @WebMethod(operationName = "GetLastMatchByLeagueTeam", action = "http://msiggi.de/Sportsdata/Webservices/GetLastMatchByLeagueTeam")
    @RequestWrapper(localName = "GetLastMatchByLeagueTeam", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetLastMatchByLeagueTeam")
    @ResponseWrapper(localName = "GetLastMatchByLeagueTeamResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetLastMatchByLeagueTeamResponse")
    @WebResult(name = "GetLastMatchByLeagueTeamResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.Matchdata getLastMatchByLeagueTeam(
        @WebParam(name = "leagueId", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int leagueId,
        @WebParam(name = "teamId", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int teamId
    );

    /**
     * Gibt das Datum der letzten Änderung in der als Parameter zu übergebenden Liga + Saison zurueck. Kann verwendet werden, um clientseitg unnötige Abfragen zu vermeiden (Cache)
     */
    @WebMethod(operationName = "GetLastChangeDateByGroupLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetLastChangeDateByGroupLeagueSaison")
    @RequestWrapper(localName = "GetLastChangeDateByGroupLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetLastChangeDateByGroupLeagueSaison")
    @ResponseWrapper(localName = "GetLastChangeDateByGroupLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetLastChangeDateByGroupLeagueSaisonResponse")
    @WebResult(name = "GetLastChangeDateByGroupLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public javax.xml.datatype.XMLGregorianCalendar getLastChangeDateByGroupLeagueSaison(
        @WebParam(name = "groupOrderID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int groupOrderID,
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );

    /**
     * Gibt eine Struktur aller verfügbaren Ligen zurück! Erwartet keine Parameter.
     */
    @WebMethod(operationName = "GetAvailLeagues", action = "http://msiggi.de/Sportsdata/Webservices/GetAvailLeagues")
    @RequestWrapper(localName = "GetAvailLeagues", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetAvailLeagues")
    @ResponseWrapper(localName = "GetAvailLeaguesResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetAvailLeaguesResponse")
    @WebResult(name = "GetAvailLeaguesResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfLeague getAvailLeagues();

    /**
     * Gibt einen serialisiertes JSON-Objekt von Sport-Spieldaten zurueck. Als Parameter werden eine groupOrderID (zu entnehmen aus GetAvailGroups, entspricht z.B. bei der Fussball-Bundesliga dem Spieltag), der Liga-Shortcut (z.B. 'bl1') sowie die Saison (aus GetAvailLeagues, z.B. '2009') erwartet.
     */
    @WebMethod(operationName = "GetMatchdataByGroupLeagueSaisonJSON", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByGroupLeagueSaisonJSON")
    @RequestWrapper(localName = "GetMatchdataByGroupLeagueSaisonJSON", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByGroupLeagueSaisonJSON")
    @ResponseWrapper(localName = "GetMatchdataByGroupLeagueSaisonJSONResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByGroupLeagueSaisonJSONResponse")
    @WebResult(name = "GetMatchdataByGroupLeagueSaisonJSONResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public java.lang.String getMatchdataByGroupLeagueSaisonJSON(
        @WebParam(name = "groupOrderID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int groupOrderID,
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );

    /**
     * Gibt eine Liste der verfügbaren Sportarten, für welche gültige Ligen bestehen, zurück. Erwartet keine Parameter
     */
    @WebMethod(operationName = "GetAvailSports", action = "http://msiggi.de/Sportsdata/Webservices/GetAvailSports")
    @RequestWrapper(localName = "GetAvailSports", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetAvailSports")
    @ResponseWrapper(localName = "GetAvailSportsResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetAvailSportsResponse")
    @WebResult(name = "GetAvailSportsResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfSport getAvailSports();

    /**
     * Gibt eine Liste der GoalGetter der als Parameter zu übergebenden Liga + Saison zurueck.
     */
    @WebMethod(operationName = "GetGoalGettersByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetGoalGettersByLeagueSaison")
    @RequestWrapper(localName = "GetGoalGettersByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetGoalGettersByLeagueSaison")
    @ResponseWrapper(localName = "GetGoalGettersByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetGoalGettersByLeagueSaisonResponse")
    @WebResult(name = "GetGoalGettersByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfGoalGetter getGoalGettersByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );

    /**
     * Gibt das Datum der letzten Änderung in der als Parameter zu übergebenden Liga + Saison zurueck. Kann verwendet werden, um clientseitg unnötige Abfragen zu vermeiden (Cache)
     */
    @WebMethod(operationName = "GetLastChangeDateByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetLastChangeDateByLeagueSaison")
    @RequestWrapper(localName = "GetLastChangeDateByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetLastChangeDateByLeagueSaison")
    @ResponseWrapper(localName = "GetLastChangeDateByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetLastChangeDateByLeagueSaisonResponse")
    @WebResult(name = "GetLastChangeDateByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public javax.xml.datatype.XMLGregorianCalendar getLastChangeDateByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );

    /**
     * Gibt eine Struktur aller verfügbaren Ligen für die zu übergebende SportID zurück. Diese ist aus 'GetAvailSports()' zu entnehmen!
     */
    @WebMethod(operationName = "GetAvailLeaguesBySports", action = "http://msiggi.de/Sportsdata/Webservices/GetAvailLeaguesBySports")
    @RequestWrapper(localName = "GetAvailLeaguesBySports", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetAvailLeaguesBySports")
    @ResponseWrapper(localName = "GetAvailLeaguesBySportsResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetAvailLeaguesBySportsResponse")
    @WebResult(name = "GetAvailLeaguesBySportsResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfLeague getAvailLeaguesBySports(
        @WebParam(name = "sportID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int sportID
    );

    /**
     * Gibt die aktuelle groupOrderID (entspricht z.B. bei der Fussball-Bundesliga dem 'Spieltag') des als Parameter zu übergebenden leagueShortcuts (z.B. 'bl1') aus. Der aktuelle Spieltag wird jeweils zur Hälfte der Zeit zwischen dem letzten Spiel des letzten Spieltages und dem ersten Spiel des nächsten Spieltages erhöht.
     */
    @WebMethod(operationName = "GetCurrentGroupOrderID", action = "http://msiggi.de/Sportsdata/Webservices/GetCurrentGroupOrderID")
    @RequestWrapper(localName = "GetCurrentGroupOrderID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetCurrentGroupOrderID")
    @ResponseWrapper(localName = "GetCurrentGroupOrderIDResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetCurrentGroupOrderIDResponse")
    @WebResult(name = "GetCurrentGroupOrderIDResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public int getCurrentGroupOrderID(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut
    );

    /**
     * Gibt eine Struktur des  nächsten anstehenden Spieles des als Parameter zu übergebenden Teams der ebenfalls zu übergebenen Liga zurueck.
     */
    @WebMethod(operationName = "GetNextMatchByLeagueTeam", action = "http://msiggi.de/Sportsdata/Webservices/GetNextMatchByLeagueTeam")
    @RequestWrapper(localName = "GetNextMatchByLeagueTeam", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetNextMatchByLeagueTeam")
    @ResponseWrapper(localName = "GetNextMatchByLeagueTeamResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetNextMatchByLeagueTeamResponse")
    @WebResult(name = "GetNextMatchByLeagueTeamResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.Matchdata getNextMatchByLeagueTeam(
        @WebParam(name = "leagueId", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int leagueId,
        @WebParam(name = "teamId", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int teamId
    );

    /**
     * Gibt eine Struktur des zuletzt ausgetragenen Spieles der als Parameter zu übergebenden Liga zurueck.
     */
    @WebMethod(operationName = "GetLastMatch", action = "http://msiggi.de/Sportsdata/Webservices/GetLastMatch")
    @RequestWrapper(localName = "GetLastMatch", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetLastMatch")
    @ResponseWrapper(localName = "GetLastMatchResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetLastMatchResponse")
    @WebResult(name = "GetLastMatchResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.Matchdata getLastMatch(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut
    );

    /**
     * Gibt eine Struktur von Sport-Spieldaten zurueck. Die Beginn-Zeit der ausgegebenen Spieldaten liegt zwischen den als Parameter zu übergebenen DateTime-Werten. (fromDateTime <= matchBeginDateTime < toDateTime)Als weiterer Parameter wird der Liga-Shortcut (z.B. 'bl1') erwartet.
     */
    @WebMethod(operationName = "GetMatchdataByLeagueDateTime", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByLeagueDateTime")
    @RequestWrapper(localName = "GetMatchdataByLeagueDateTime", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByLeagueDateTime")
    @ResponseWrapper(localName = "GetMatchdataByLeagueDateTimeResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByLeagueDateTimeResponse")
    @WebResult(name = "GetMatchdataByLeagueDateTimeResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfMatchdata getMatchdataByLeagueDateTime(
        @WebParam(name = "fromDateTime", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        javax.xml.datatype.XMLGregorianCalendar fromDateTime,
        @WebParam(name = "toDateTime", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        javax.xml.datatype.XMLGregorianCalendar toDateTime,
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut
    );

    /**
     * Gibt eine Struktur von Sport-Spieldaten zurueck. Als Parameter werden eine groupOrderID (zu entnehmen aus GetAvailGroups, entspricht z.B. bei der Fussball-Bundesliga dem Spieltag), der Liga-Shortcut (z.B. 'bl1') sowie die Saison (aus GetAvailLeagues, z.B. '2009') erwartet.
     */
    @WebMethod(operationName = "GetMatchdataByGroupLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByGroupLeagueSaison")
    @RequestWrapper(localName = "GetMatchdataByGroupLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByGroupLeagueSaison")
    @ResponseWrapper(localName = "GetMatchdataByGroupLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByGroupLeagueSaisonResponse")
    @WebResult(name = "GetMatchdataByGroupLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfMatchdata getMatchdataByGroupLeagueSaison(
        @WebParam(name = "groupOrderID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int groupOrderID,
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );

    /**
     * Gibt eine Liste aller Goals des als Parameter zu übergebenden Match zurueck.
     */
    @WebMethod(operationName = "GetGoalsByMatch", action = "http://msiggi.de/Sportsdata/Webservices/GetGoalsByMatch")
    @RequestWrapper(localName = "GetGoalsByMatch", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetGoalsByMatch")
    @ResponseWrapper(localName = "GetGoalsByMatchResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetGoalsByMatchResponse")
    @WebResult(name = "GetGoalsByMatchResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfGoal getGoalsByMatch(
        @WebParam(name = "MatchID", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int matchID
    );

    /**
     * Gibt eine Struktur von Matches zurück, bei welchen die als Parameter übergebenen Teams gegeneinander spielten.
     */
    @WebMethod(operationName = "GetMatchdataByTeams", action = "http://msiggi.de/Sportsdata/Webservices/GetMatchdataByTeams")
    @RequestWrapper(localName = "GetMatchdataByTeams", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByTeams")
    @ResponseWrapper(localName = "GetMatchdataByTeamsResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetMatchdataByTeamsResponse")
    @WebResult(name = "GetMatchdataByTeamsResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfMatchdata getMatchdataByTeams(
        @WebParam(name = "teamID1", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int teamID1,
        @WebParam(name = "teamID2", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int teamID2
    );

    /**
     * Gibt eine Struktur deutscher Fussball-Spieldaten zurueck. Diese Methode steht nur noch aus Gründen der Kompatibilität zu älteren Applikationen zur Verfügung. Bitte nutzen sie vorrangig die GetMatchdata... - Methoden!
     */
    @WebMethod(operationName = "GetFusballdaten", action = "http://msiggi.de/Sportsdata/Webservices/GetFusballdaten")
    @RequestWrapper(localName = "GetFusballdaten", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetFusballdaten")
    @ResponseWrapper(localName = "GetFusballdatenResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetFusballdatenResponse")
    @WebResult(name = "GetFusballdatenResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfFussballdaten getFusballdaten(
        @WebParam(name = "Spieltag", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int spieltag,
        @WebParam(name = "Liga", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String liga,
        @WebParam(name = "Saison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        int saison,
        @WebParam(name = "Userkennung", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String userkennung
    );

    /**
     * Gibt eine Liste aller Teams der als Parameter zu übergebenden Liga + Saison zurueck.
     */
    @WebMethod(operationName = "GetTeamsByLeagueSaison", action = "http://msiggi.de/Sportsdata/Webservices/GetTeamsByLeagueSaison")
    @RequestWrapper(localName = "GetTeamsByLeagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetTeamsByLeagueSaison")
    @ResponseWrapper(localName = "GetTeamsByLeagueSaisonResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetTeamsByLeagueSaisonResponse")
    @WebResult(name = "GetTeamsByLeagueSaisonResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfTeam getTeamsByLeagueSaison(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );

    /**
     * Gibt eine Liste der bereits eingetragenen Spiel-Einteilungen (Spieltag, Vorrunde, Finale, ...) der als Parameter zu übergebenden Liga + Saison zurueck.
     */
    @WebMethod(operationName = "GetAvailGroups", action = "http://msiggi.de/Sportsdata/Webservices/GetAvailGroups")
    @RequestWrapper(localName = "GetAvailGroups", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetAvailGroups")
    @ResponseWrapper(localName = "GetAvailGroupsResponse", targetNamespace = "http://msiggi.de/Sportsdata/Webservices", className = "de.msiggi.sportsdata.webservices.GetAvailGroupsResponse")
    @WebResult(name = "GetAvailGroupsResult", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
    public de.msiggi.sportsdata.webservices.ArrayOfGroup getAvailGroups(
        @WebParam(name = "leagueShortcut", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueShortcut,
        @WebParam(name = "leagueSaison", targetNamespace = "http://msiggi.de/Sportsdata/Webservices")
        java.lang.String leagueSaison
    );
}
