package de.msiggi.sportsdata.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-06T14:08:10.099+02:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "Sportsdata", 
                  wsdlLocation = "http://www.OpenLigaDB.de/Webservices/Sportsdata.asmx?WSDL",
                  targetNamespace = "http://msiggi.de/Sportsdata/Webservices") 
public class Sportsdata extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://msiggi.de/Sportsdata/Webservices", "Sportsdata");
    public final static QName SportsdataSoap = new QName("http://msiggi.de/Sportsdata/Webservices", "SportsdataSoap");
    public final static QName SportsdataSoap12 = new QName("http://msiggi.de/Sportsdata/Webservices", "SportsdataSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://www.OpenLigaDB.de/Webservices/Sportsdata.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Sportsdata.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.OpenLigaDB.de/Webservices/Sportsdata.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public Sportsdata(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Sportsdata(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sportsdata() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sportsdata(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sportsdata(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sportsdata(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap")
    public SportsdataSoap getSportsdataSoap() {
        return super.getPort(SportsdataSoap, SportsdataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap")
    public SportsdataSoap getSportsdataSoap(WebServiceFeature... features) {
        return super.getPort(SportsdataSoap, SportsdataSoap.class, features);
    }
    /**
     *
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap12")
    public SportsdataSoap getSportsdataSoap12() {
        return super.getPort(SportsdataSoap12, SportsdataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SportsdataSoap
     */
    @WebEndpoint(name = "SportsdataSoap12")
    public SportsdataSoap getSportsdataSoap12(WebServiceFeature... features) {
        return super.getPort(SportsdataSoap12, SportsdataSoap.class, features);
    }

}
